### ISSUE TITLE
在最新上游更新后所有bukkit插件兼容全部失效

### ISSUE THREAD

**Issue by buildin1** [Era4FunMC/Molia#1]
在最新上游更新后所有bukkit插件兼容全部失效，再更新最新上游之前可以兼容绝大部分的bukkit插件，经过测试，再更新前的那个版本加载插件均无报错，但在更新最新上游后的左右版本运行bukkit插件都会报错插件不是最新版，哪怕已经是最新的插件依旧会有这个报错

**Comment by ghost** [comment]
> 在最新上游更新后所有bukkit插件兼容全部失效，再更新最新上游之前可以兼容绝大部分的bukkit插件，经过测试，再更新前的那个版本加载插件均无报错，但在更新最新上游后的左右版本运行bukkit插件都会报错插件不是最新版，哪怕已经是最新的插件依旧会有这个报错
> 

bukkit兼容已经全部迁移到dirtymolia了((忘记更新readme了)
