### ISSUE TITLE
TODO:Fix unusable gravity block duping config issue

### ISSUE THREAD

**Issue by MrHua269** [Era4FunMC/Molia#2]

**Comment by WarSkyGod** [comment]
亲测你需要kaiiju的https://github.com/KaiijuMC/Kaiiju/blob/ver/1.20.1/patches/server/0022-Toggle-safe-teleportation.patch这个补丁，然后在配置文件开启刷沙和关闭安全传送即可修复

**Comment by WarSkyGod** [comment]
https://pan.craft-hello.top/api/raw/?path=/%E5%88%86%E4%BA%AB/Molia-paperclip-1.20.1-R0.1-SNAPSHOT-reobf.jar&odpt=60af5972a08c6aeffc69ee0d5c8583e5f9aec399f6b8cd3c07155e7ee9949fb6 这是我自己编译的版本

**Comment by ghost** [comment]
> 亲测你需要kaiiju的https://github.com/KaiijuMC/Kaiiju/blob/ver/1.20.1/patches/server/0022-Toggle-safe-teleportation.patch这个补丁，然后在配置文件开启刷沙和关闭安全传送即可修复

哇，十分感谢，明天回来就修()

**Comment by ghost** [comment]
Done
