### ISSUE TITLE
[Feature Request] Pufferfish Entity Timeout

### ISSUE THREAD

**Issue by R00tB33rMan** [Era4FunMC/Molia#3]
Pufferfish's Entity TTL allows server owners to set the length of each individual projectile's lifetime, mitigating server (or in this case) regionized overload. Having too many snowballs and/or experience bottled (most common lag-inducing projectiles due to scalability) causes TPS + MSPT to massively depreciate and would be vastly useful for myself and others, without the need for an external plugin to conduct the same task(s).

Appreciate what you have going here and hopefully this is doable!

Patch: https://github.com/pufferfish-gg/Pufferfish/blob/ver/1.20/patches/server/0042-Entity-TTL.patch

**Comment by ghost** [comment]
Completed at commit 49cf4cca9cb8f5e02be47a494c0c0de4ca47dea4 in Molia and a1626866210dc29ad352fc550ec347f2f57f2a25 in DirtyMolia
