### ISSUE TITLE
1.20.2 update？

### ISSUE THREAD

**Issue by MineSunshineone** [Era4FunMC/Molia#4]

**Comment by ghost** [comment]
I am waiting folia for a stable 1.20.2 version.

**Comment by MineSunshineone** [comment]
Maybe a dev ver? i want test it！

**Comment by ghost** [comment]
> Maybe a dev ver? i want test it！

I will create dev/1.20.2 on Sunday(Maybe? I don't have too much free time,So I am sorry about that.)

**Comment by ghost** [comment]
See branch dev/1.20.2
